[package]
name = "scap"
version = "0.0.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
description = "A remote repository management CLI in Rust, a port of x-motemen/ghq."
repository = "https://github.com/zchee/scap"
readme = "README.md"

[dependencies]
anyhow = "1"
bstr = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
dirs = "6"
fs2 = "0.4"
gix-url = "0.36"
regex = "1.12.3"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
serial_test = "3.4.0"
tempfile = "3"
