#!/usr/bin/env bash
# Build the deterministic repository tree the CodSpeed walltime benchmarks
# (codspeed.yaml) run `scap root` and `scap list` against.
#
# The tree is generated rather than committed so the same three numbers --
# hosts, owners, repositories -- fix its shape on every machine, and so the
# 1800 repositories cost nothing in the git history. A repository is marked
# by a `.git` DIRECTORY made with `mkdir`, not by `git init`: `scap list`
# only tests for the marker's presence, so a real repository would add
# several thousand file writes and change nothing the walker measures.
#
# Layout, with <base> defaulting to target/bench-fixture (already ignored by
# .gitignore's `target` rule):
#
#   <base>/gitconfig                             GIT_CONFIG_GLOBAL fixture,
#                                                sets scap.root to <base>/root
#   <base>/root/<host>/<owner>/<repo>/.git       1800 repositories
#   <base>/root/<host>/_notes/<a>/<b>/           non-repository subtrees,
#                                                which the walk must descend
#                                                into and list nothing from
#
# `scap list` on this tree prints exactly HOSTS x OWNERS x REPOS lines.
#
# Usage: scripts/bench-fixture.sh [<base>]
set -euo pipefail

# The shape. Changing any of these changes every recorded benchmark, so
# treat them the way the plan treats a frozen threshold.
HOSTS=(github.com gitlab.com git.sr.ht)
OWNERS=40
REPOS=15
# Non-repository subtrees per host, each three levels deep.
NOISE_TREES=3
NOISE_DEPTH=3

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
base_arg="${1:-target/bench-fixture}"
case "$base_arg" in
    /*) base="$base_arg" ;;
    *) base="$REPO_ROOT/$base_arg" ;;
esac
root="$base/root"

rm -rf "$base"
mkdir -p "$root"

# Emit every directory to create on stdout, then hand the whole list to
# `mkdir -p` in batches. Spawning one `mkdir` per repository would dominate
# the script's runtime for no benefit.
emit_dirs() {
    local host owner repo tree level path
    for host in "${HOSTS[@]}"; do
        for ((owner = 0; owner < OWNERS; owner++)); do
            for ((repo = 0; repo < REPOS; repo++)); do
                printf '%s/%s/owner-%03d/repo-%03d/.git\n' "$root" "$host" "$owner" "$repo"
            done
        done
        for ((tree = 0; tree < NOISE_TREES; tree++)); do
            path="$(printf '%s/%s/_notes-%d' "$root" "$host" "$tree")"
            for ((level = 0; level < NOISE_DEPTH; level++)); do
                path="$path/level-$level"
            done
            printf '%s\n' "$path"
        done
    done
}

emit_dirs | xargs -n 128 mkdir -p

# The configuration the benchmarks read. `scap.root` is absolute because the
# exec harness runs the binary from the repository root, not from here.
cat >"$base/gitconfig" <<EOF
# Generated by scripts/bench-fixture.sh -- do not edit, it is rewritten on
# every run.
[scap]
	root = $root
EOF

repos=$((${#HOSTS[@]} * OWNERS * REPOS))
noise=$((${#HOSTS[@]} * NOISE_TREES))
# Count the markers actually on disk rather than trusting the arithmetic:
# the glob is the same <host>/<owner>/<repo>/.git shape the walker looks for,
# so a partially written tree is caught here instead of in a benchmark
# number nobody can explain later.
shopt -s nullglob
markers=("$root"/*/*/*/.git)
marker_count="${#markers[@]}"

printf 'bench-fixture: base=%s\n' "$base"
printf 'bench-fixture: hosts=%d owners=%d repos-per-owner=%d\n' \
    "${#HOSTS[@]}" "$OWNERS" "$REPOS"
printf 'bench-fixture: repositories=%d (.git markers on disk=%s)\n' \
    "$repos" "$marker_count"
printf 'bench-fixture: non-repository subtrees=%d (%d levels each)\n' \
    "$noise" "$NOISE_DEPTH"
printf 'bench-fixture: gitconfig=%s\n' "$base/gitconfig"

if [[ "$marker_count" != "$repos" ]]; then
    printf 'bench-fixture: expected %d .git markers, found %s\n' \
        "$repos" "$marker_count" >&2
    exit 1
fi
